version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: |
          docker-compose -f docker-compose.test.yml -p ci build
          docker-compose -f docker-compose.test.yml -p ci up -d
          cd tests && ./test.sh
          echo "--------------------"
          'docker logs -f ci_sut_1; echo "Exited with status code: $(docker wait ci_sut_1)"; exit $(docker wait ci_sut_1)'
#      - run: 'docker logs -f ci_sut_1; echo "Exited with status code: $(docker wait ci_sut_1)"; exit $(docker wait ci_sut_1)'

  deploy_dev:
    machine: true
    steps:
      - checkout

      # Login to docker
#      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
#
#      # Build our images
#      - run: docker-compose -f docker-compose.test.yml -p ci build

      # Tag ahead of release
      - run: |
          docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
          docker-compose -f docker-compose.test.yml -p ci build
          docker tag ci_web1804-php7:latest mattrayner/lamp:latest
          docker tag ci_web1804-php7:latest mattrayner/lamp:latest-1804
          docker tag ci_web1804-php7:latest mattrayner/lamp:latest-1804-php7
          docker tag ci_web1604-php7:latest mattrayner/lamp:latest-1604
          docker tag ci_web1604-php7:latest mattrayner/lamp:latest-1604-php7
          docker push mattrayner/lamp:latest
          docker push mattrayner/lamp:latest-1804
          docker push mattrayner/lamp:latest-1804-php7
          docker push mattrayner/lamp:latest-1604
          docker push mattrayner/lamp:latest-1604-php7

      # Push images
#      - run: |
#          docker push mattrayner/lamp:latest
#          docker push mattrayner/lamp:latest-1804
#          docker push mattrayner/lamp:latest-1804-php7
#          docker push mattrayner/lamp:latest-1604
#          docker push mattrayner/lamp:latest-1604-php7

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
